version: "3.8"

services:
  keycloak-postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_PG_DATABASE}
      POSTGRES_USER: ${KEYCLOAK_PG_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
  keycloak-postgres-dbeaver:
    image: dbeaver/cloudbeaver:latest
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
    ports:
      - ${DBEAVER_PORT}:8978
    depends_on:
      - keycloak-postgres
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_PG_DATABASE}
      DB_USER: ${KEYCLOAK_PG_USERNAME}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - keycloak-postgres
    command: "start-dev"
  keycloak-frontend-app-one:
    build:
      context: "./keycloak-frontend-poc"
      dockerfile: "./Dockerfile"
    ports:
      - ${FRONTEND_APP_ONE_PORT}:3000
    env_file:
      - '.env.react.one'
    volumes:
      - ./keycloak-frontend-poc:/frontend-app
      - /frontend-app/node_modules
    restart: unless-stopped
    depends_on:
      - keycloak
  keycloak-frontend-app-two:
    build:
      context: "./keycloak-frontend-poc"
      dockerfile: "./Dockerfile"
    ports:
      - ${FRONTEND_APP_TWO_PORT}:3000
    env_file:
      - '.env.react.two'
    volumes:
      - ./keycloak-frontend-poc:/frontend-app
      - /frontend-app/node_modules
    restart: unless-stopped
    depends_on:
      - keycloak

volumes:
  postgres_data:
    driver: local
  dbeaver_data:
    driver: local
