version: "3.8"

services:
  keycloak-postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_PG_DATABASE}
      POSTGRES_USER: ${KEYCLOAK_PG_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_PG_DATABASE}
      DB_USER: ${KEYCLOAK_PG_USERNAME}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    command: "start-dev"
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - keycloak-postgres

volumes:
  postgres_data:
    driver: local
